Bill s temp
ARISEAdaptiveDesign/WildThing-Collaboration pull request #7
Opened 2022-09-30 21:15 UTC by tracyofleming

So I'm trying to update the files in BILLS_temp branch with the files that were replaced with the local files that were most recently tested. Then we can get Tyler to help us merge them back into Main.

2022-09-30 22:08 UTC, 12tbuchman requested changes
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 6 of 6 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7)* status: 6 of 7 files reviewed, 18 unresolved discussions (waiting on @12tbuchman and @tracyofleming)

___
*[`-- commits` line 17 at r3](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFOjkY0gteA7TEtbXo):*
please combine these commits. each commit should be able to live on it's own so if you have typos in one commit it is best practice to fix the typos and combine the commits
___
*[`-- commits` line 33 at r7](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFQvDKC1yfzFqalTyY):*
this comment doesnt really describe the changes that were made. It looks like most of the changes are related to braking parameters so the commit should be about that.
___
*[`README.md` line 4 at r2](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFN_LHB0q4D88WX_zn:-NDFN_LHB0q4D88WX_zo:b-xyexgz) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/9260141654a76cd0e12257c7eee6764dc1dd2645/README.md#L4)):*
> ```Markdown
> Controls for Wild Thing Conversion
> 
> 2022-07-21 v4.3 from v4.2
> ```

We really don't need to keep a "change log" as git does that for us. I would advise that the Readme be a place to read how to operate the code, but we can get rid of the changelog entirely.
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 294 at r2](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFNlt237_2Vj2eh07l:-NDFNlt237_2Vj2eh07m:b-7jkxnn) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/9260141654a76cd0e12257c7eee6764dc1dd2645/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L294)):*
> ```cpp
>       break;
>       case 3:
>         if (motorLVel_Final==0){
> ```

please add spacing, should be `if (motorLVel_Final == 0) {`
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 295 at r2](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFNwDL1pDUv4lKTjZ4:-NDFNwDL1pDUv4lKTjZ5:b-9m7zjh) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/9260141654a76cd0e12257c7eee6764dc1dd2645/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L295)):*
> ```cpp
>       case 3:
>         if (motorLVel_Final==0){
>           BrakeL = min(BrakeL+BrakeRamp),400); //increment brake at defined rate to avoid skids ;), Limit at 400
> ```

please add spacing
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 302 at r2](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFOLKB7BiqT0rTZFRy:-NDFOLKB7BiqT0rTZFRz:b50ikpo) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/9260141654a76cd0e12257c7eee6764dc1dd2645/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L302)):*
> ```cpp
>           md.setM1Speed(motorLSpeed);
>         }
>         if (motorRVel_Final==0){
> ```

please add spacing as above
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 310 at r2](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFOTfTDlULpvrGXGaM:-NDFOTfTDlULpvrGXGaN:bjpkxz) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/9260141654a76cd0e12257c7eee6764dc1dd2645/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L310)):*
> ```cpp
>           md.setM2Speed(motorRSpeed);
>         }
>         //stopIfFault();
> ```

what does this comment mean?
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 157 at r5](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFPFUQ0uuaaqsgjekG:-NDFPFUQ0uuaaqsgjekH:b9r4mqv) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/c016c34cf2cbc4fdc05c8107b5413a2a1f22d98c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L157)):*
> ```cpp
>       if ( joyAngle<=x2 ) {
>         if (x2==x1) {Lmix = y1;} else {  Lmix = y1 + (joyAngle - x1) * (y2 - y1) / (x2 - x1);}
>         //Serial.print("LIndex= "); Serial.print(i); Serial.print("  ");
> ```

do we need these debug statements in the upstream code? if they were for development it is usually best practice to remove them before committing
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 170 at r5](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFPIbF8JeSvxXS5-Kl:-NDFPIbF8JeSvxXS5-Km:bnj7hl0) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/c016c34cf2cbc4fdc05c8107b5413a2a1f22d98c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L170)):*
> ```cpp
>       if ( joyAngle<=x2 ) {
>         if (x2==x1) {Rmix = y1;} else {  Rmix = y1 + (joyAngle - x1) * (y2 - y1) / (x2 - x1);}
>         //Serial.print("RIndex= "); Serial.print(i); Serial.print("  "); 
> ```

same as above
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 45 at r7](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFQozMBCM8Exgkdt3P:-NDFQozMBCM8Exgkdt3Q:b73mlh1) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/42aff1b7b66ea5898e9789abb6a819f8a632f04c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L45)):*
> ```cpp
>         ///////////////////////////////////////////////////////////////////////////////////////////////////
>           delay(50); // wait a little before turning on Motor Controllers
> o
> ```

is this meant to be there?
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 297 at r7](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFRISA-HiF7JCYWjwU:-NDFRISB66BM79l0xk5K:bj07pyo) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/42aff1b7b66ea5898e9789abb6a819f8a632f04c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L297)):*
> ```cpp
>       case 3:
>         if (motorLVel_Final==0){
>           BrakeL = min(BrakeL+BrakeRamp,maxBrake); //increment brake at defined rate to avoid skids ;), Limit at maxBrake
> ```

there should be a space before `maxBrake`
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 305 at r7](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFRLZw4awELybVzd10:-NDFRLZw4awELybVzd11:bnj7hl0) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/42aff1b7b66ea5898e9789abb6a819f8a632f04c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L305)):*
> ```cpp
>         }
>         if (motorRVel_Final==0){
>           BrakeR = min(BrakeR+BrakeRamp,maxBrake); //increment brake at defined rate to avoid skids ;), limit at maxBrake
> ```

same as above
___
*[`ARISE_WildThing_MEGA/CalibrationJoystick.h` line 24 at r5](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFPT0_0JGg7Ox4Fm8x:-NDFPT0_0JGg7Ox4Fm8y:b-vg0p4i) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/c016c34cf2cbc4fdc05c8107b5413a2a1f22d98c/ARISE_WildThing_MEGA/CalibrationJoystick.h#L24)):*
> ```objc
>   // Angles
>   const float spinZone      = 15; // number of degrees above or below East or West that one motor turning and other is stopped
>   const float TrimAngle = 10; // degrees travel on either side of forward/backward that is treated as true forward/backward
> ```

all of your other variables here are lowerCamelCase but these new names are UpperCamelCase. Should it be consistent?
___
*[`ARISE_WildThing_MEGA/CalibrationJoystick.h` line 32 at r5](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFQ8Mr6JljrpddZgzC:-NDFQ8Mr6JljrpddZgzD:bnj7hl0) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/c016c34cf2cbc4fdc05c8107b5413a2a1f22d98c/ARISE_WildThing_MEGA/CalibrationJoystick.h#L32)):*
> ```objc
>   const float motorTurnRev_PowerLevels = 0.70 ; // range: 0.01 to 1 motor speeds u [...]

2022-10-01 01:02 UTC, tracyofleming commented
Tyler,
Thanks for reviewing the pull request. Let's see if this all makes more
sense to Bill. I'm going to forward this on to him, as I have no idea how
to address most of these suggestions.
Hopefully he can get to them from his account and access.

This stuff is so complicated :-(
I'm so impressed with you guys for being able to keep up with all of this
syntax detail...

tof

*Tracy Fleming*
*Optimal 3D Print Service, Optimal 3D <http://www.optimal3d.com>*
Library Board Trustee, *Mexico Public Library
<https://www.mexicopubliclibrary.org/>*
Adaptive Design Fabricator, *ARISE Inc
<https://ariseinc.org/advocacy-accessibility/arise-adaptive-design/>.*
Records Assistant, *Center for Instruction, Technology, and Innovation
<https://www.citiboces.org/> *
315-806-8906
***@***.***


On Fri, Sep 30, 2022 at 6:08 PM Tyler Buchman ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 2 of
> 2 files at r4, 6 of 6 files at r5, 1 of 1 files at r6, 1 of 2 files at r7,
> all commit messages.
> *Reviewable
> <https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7>*
> status: 6 of 7 files reviewed, 18 unresolved discussions (waiting on
> @12tbuchman <https://github.com/12tbuchman> and @tracyofleming
> <https://github.com/tracyofleming>)
>
> ------------------------------
>
> *-- commits line 17 at r3
> <https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFOjkY0gteA7TEtbXo>:*
> please combine these commits. each commit should be able to live on it's
> own so if you have typos in one commit it is best practice to fix the typos
> and combine the commits
> ------------------------------
>
> *-- commits line 33 at r7
> <https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFQvDKC1yfzFqalTyY>:*
> this comment doesnt really describe the changes that were made. It looks
> like most of the changes are related to braking parameters so the commit
> should be about that.
> ------------------------------
>
> *README.md line 4 at r2
> <https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFN_LHB0q4D88WX_zn:-NDFN_LHB0q4D88WX_zo:b-xyexgz>
> (raw file
> <https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/9260141654a76cd0e12257c7eee6764dc1dd2645/README.md#L4>):*
>
> Controls for Wild Thing Conversion
>
> 2022-07-21 v4.3 from v4.2
>
> We really don't need to keep a "change log" as git does that for us. I
> would advise that the Readme be a place to read how to operate the code,
> but we can get rid of the changelog entirely.
> ------------------------------
>
> *ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino line 294 at r2
> <https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFNlt237_2Vj2eh07l:-NDFNlt237_2Vj2eh07m:b-7jkxnn>
> (raw file
> <https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/9260141654a76cd0e12257c7eee6764dc1dd2645/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L294>):*
>
>       break;
>       case 3:
>         if (motorLVel_Final==0){
>
> please add spacing, should be if (motorLVel_Final == 0) {
> ------------------------------
>
> *ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino line 295 at r2
> <https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFNwDL1pDUv4lKTjZ4:-NDFNwDL1pDUv4lKTjZ5:b-9m7zjh>
> (raw file
> <https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/9260141654a76cd0e12257c7eee6764dc1dd2645/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L295>):*
>
>       case 3:
>         if (motorLVel_Final==0){
>           BrakeL = min(BrakeL+BrakeRamp),400); //increment brake at defined rate to avoid skids ;), Limit at 400
>
> please add spacing
> ------------------------------
>
> *ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino line 302 at r2
> <https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFOLKB7BiqT0rTZFRy:-NDFOLKB7BiqT0rTZFRz:b50ikpo>
> (raw file
> <https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/9260141654a76cd0e12257c7eee6764dc1dd2645/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L302>):*
>
>           md.setM1Speed(motorLSpeed);
>         }
>         if (motorRVel_Final==0){
>
> please add spacing as above
> ------------------------------
>
> *ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino line 310 at r2
> <https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFOTfTDlULpvrGXGaM:-NDFOTfTDlULpvrGXGaN:bjpkxz>
> (raw file
> <https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/9260141654a76cd0e12257c7eee6764dc1dd2645/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L310>):*
>
>           md.setM2Speed(motorRSpeed);
>         }
>         //stopIfFault();
>
> what does this comment mean?
> ------------------------------
>
> *ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino line 157 at r5
> <https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFPFUQ0uuaaqsgjekG:-NDFPFUQ0uuaaqsgjekH:b9r4mqv>
> (raw file
> <https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/c016c34cf2cbc4fdc05c8107b5413a2a1f22d98c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L157>):*
>
>       if ( joyAngle<=x2 ) {
>         if (x2==x1) {Lmix = y1;} else {  Lmix = y1 + (joyAngle - x1) * (y2 - y1) / (x2 - x1);}
>         //Serial.print("LIndex= "); Serial.print(i); Serial.print("  ");
>
> do we need these debug statements in the upstream code? if they were for
> development it is usually best practice to remove them before committing
> ------------------------------
>
> *ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino line 170 at r5
> <https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFPIbF8JeSvxXS5-Kl:-NDFPIbF8JeSvxXS5-Km:bnj7hl0>
> (raw file
> <https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/c016c34cf2cbc4fdc05c8107b5413a2a1f22d98c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L170>):*
>
>       if ( joyAngle<=x2 ) {
>         if (x2==x1) {Rmix = y1;} else {  Rmix = y1 + (joyAngle - x1) * (y2 - y1) / (x2 - x1);}
>         //Serial.print("RIndex= "); Serial.print(i); Serial.print("  ");
>
> same as above
> ------------------------------
>
> *ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino line 45 at r7
> <https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFQozMBCM8Exgkdt3P:-NDFQozMBCM8Exgkdt3Q:b73mlh1>
> (raw file
> <https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/42aff1b7b66ea5898e9789abb6a819f8a632f04c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L45>):*
>
>         ///////////////////////////////////////////////////////////////////////////////////////////////////
>           delay(50); // wait a little before turning on Motor Controllers
> o
>
> is this meant to be there?
> ------------------------------
>
> *ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino line 297 at r7
> <https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFRISA-HiF7JCYWjwU:-NDFRISB66BM79l0xk5K:bj07pyo>
> (raw file
> <https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/42aff1b7b66ea5898e9789abb6a819f8a632f04c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L297>):*
>
>       case 3:
>         if (motorLVel_Final==0){
>           BrakeL = min(BrakeL+BrakeRamp,maxBrake); //increment brake at defined rate to avoid skids ;), Limit at maxBrake
>
> there should be a space before maxBrake
> ------------------------------
>
> *ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino line 305 at r7
> <https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFRLZw4awELybVzd10:-NDFRLZw4awELybVzd11:bnj7hl0>
> (raw file
> <https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/42aff1b7b66ea5898e9789abb6a819f8a632f04c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L305>):*
>
>         }
>         if (motorRVel_Final==0){
>           BrakeR = min(BrakeR+BrakeRamp,maxBrake); //incr [...]

2022-10-01 18:37 UTC, BillAtBearGrove reviewed
Hey Guys -Here's my short take. 

Readability:
I agree with all the things that improve readability. Most of it's me being sloppy or indecisive or forgetting which way I used last time, and not going back yet to clean up. Whatever the reason, they aren't critical and anyone can do some housecleaning whenever it makes sense and they have the motivation.

Commits:
worth a discussion - might be on the same page and might have different thoughts. I like having the project saved ever time I end a session for the day or make significant changes or changes I'm not confident in.

Comments/Debug:
Yeah, good practice to remove in the end. But if they are occasionally useful I prefer leaving there and commenting out. 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-:-NDJmG7GAVXVDSoKLlg4:bhyj1w1)* status: 6 of 7 files reviewed, 18 unresolved discussions (waiting on @12tbuchman and @tracyofleming)

___
*[`-- commits` line 17 at r3](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFOjkY0gteA7TEtbXo):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

please combine these commits. each commit should be able to live on it's own so if you have typos in one commit it is best practice to fix the typos and combine the commits
</blockquote></details>

This would be a good discussion - I would always recommend performing a commit at the end of a session. I wouldn't think these commits have to stand on their own at all. It's good practice to have backup in case your computer dies or you want to go back to an interim step if things go off the rails. I consider this one of the primary advantages of branching, so details aren't clouding the main branch. Is it OK to keep doing this and just merge back into the main when it's a "Stand-alone" and vetted change?
___
*[`-- commits` line 33 at r7](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFQvDKC1yfzFqalTyY):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

this comment doesnt really describe the changes that were made. It looks like most of the changes are related to braking parameters so the commit should be about that.
</blockquote></details>

might have rushed the commit. The description can be updated if required.
___
*[`README.md` line 4 at r2](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFN_LHB0q4D88WX_zn:-NDJoLRy48wA7U24jh3x:bdgg85i) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/9260141654a76cd0e12257c7eee6764dc1dd2645/README.md#L4)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

We really don't need to keep a "change log" as git does that for us. I would advise that the Readme be a place to read how to operate the code, but we can get rid of the changelog entirely.
</blockquote></details>

Meh - I'm not married to it if you have a good reason to drop it. My company always kept important steps recorded in a file that is not dependent on specific software (even GitHub) to be able to have an overview of changes.


<!-- Sent from Reviewable.io -->

2022-10-01 19:15 UTC, BillAtBearGrove reviewed
> *[Reviewable](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7)* status: 6 of 7 files reviewed, 18 unresolved discussions (waiting on @12tbuchman and @tracyofleming)

___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 294 at r2](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFNlt237_2Vj2eh07l:-NDJvKUU9r3vePHSEa8H:b-p3f61c) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/9260141654a76cd0e12257c7eee6764dc1dd2645/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L294)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

please add spacing, should be `if (motorLVel_Final == 0) {`
</blockquote></details>

go for it. Good for readability. (applies to all readability items)
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 310 at r2](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFOTfTDlULpvrGXGaM:-NDJvlur37tMXbTdlr9g:b-dece3x) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/9260141654a76cd0e12257c7eee6764dc1dd2645/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L310)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

what does this comment mean?
</blockquote></details>

Oooo.. That's not actually a comment. It's a command to stop the motor driver (VNH5019 only) if there is a fault detected. It wasn't triggering right and didn't have time to figure it out so I commented it out. Could use an actual comment to that affect added to the code as reminder.
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 157 at r5](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFPFUQ0uuaaqsgjekG:-NDJueet354bk0EVVoV_:bfz5b04) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/c016c34cf2cbc4fdc05c8107b5413a2a1f22d98c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L157)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

do we need these debug statements in the upstream code? if they were for development it is usually best practice to remove them before committing
</blockquote></details>

Sure. it's good to delete if never used again, and OK to stay if we think they might be useful.
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 45 at r7](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFQozMBCM8Exgkdt3P:-NDJq16BACZtIguU7puN:b-ob88vi) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/42aff1b7b66ea5898e9789abb6a819f8a632f04c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L45)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

is this meant to be there?
</blockquote></details>

LoL - Short answer - yes it is there "on purpose" But that's a bigger discussion I'd like to have b/c it's an artifact of the 1st few versions of code.
If it is removed, then filtering and rate limit calibrations will need to be changed.
It slows the code down by 50 ms which is intended to help it run a little more consistent for things like signal processing, noise and rate limiters. I think the normal execute time for the code is around 3ms and but varies quite a lot. Increasing the overall time means the impact in % is smaller - plus has added bonus of giving the Arduino a processing rest.

I've been meaning to get rid of that delay and setup protothreads w/ like 10ms, 100ms and 1s timers. Then split the code out to things that need to run fast and things that can run slow. Haven't had the time/guts yet, Not to mention I'm still learning how to implement this in Arduino. 
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 297 at r7](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFRISA-HiF7JCYWjwU:-NDJy7bdB4eel1lh_4hb:bb7oryy) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/42aff1b7b66ea5898e9789abb6a819f8a632f04c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L297)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

there should be a space before `maxBrake`
</blockquote></details>

sure
___
*[`ARISE_WildThing_MEGA/CalibrationJoystick.h` line 24 at r5](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFPT0_0JGg7Ox4Fm8x:-NDJwO-CATW-V2Fu9IAx:bm3sp2k) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/c016c34cf2cbc4fdc05c8107b5413a2a1f22d98c/ARISE_WildThing_MEGA/CalibrationJoystick.h#L24)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

all of your other variables here are lowerCamelCase but these new names are UpperCamelCase. Should it be consistent?
</blockquote></details>

Yup. Just sloppy on my part. Whatever is most used is fine with me.
___
*[`ARISE_WildThing_MEGA/createJoystickTables.ino` line 31 at r5](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFQCjSCwQptzuRPoPU:-NDJx0Rq9v_KdtvV3386:b-9u6jrm) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/c016c34cf2cbc4fdc05c8107b5413a2a1f22d98c/ARISE_WildThing_MEGA/createJoystickTables.ino#L31)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

why is this indented?
</blockquote></details>

You mean the line beginning "for (int i = 0....." ? Dunno. 
___
*[`ARISE_WildThing_MEGA/createJoystickTables.ino` line 46 at r5](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFQMm8EBTerpd7ZZ_P:-NDJxV1s6RrR5XeL8N6g:be5hohb) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/c016c34cf2cbc4fdc05c8107b5413a2a1f22d98c/ARISE_WildThing_MEGA/createJoystickTables.ino#L46)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

should the comma be significantly indented in line with other commas?
</blockquote></details>

Yes. Orignally it was, but variables changed and so did table layout and commas got moved around. It would be good to reset/cleanup.
___
*[`ARISE_WildThing_MEGA/createJoystickTables.ino` line 54 at r5](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFQRC99A_HfeWP-_5x:-NDJxkTq5DPwAR9k7itC:bpi8l8f) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/c016c34cf2cbc4fdc05c8107b5413a2a1f22d98c/ARISE_WildThing_MEGA/createJoystickTables.ino#L54)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

please remove extra whitespace
</blockquote></details>

Or line up commas ;)


<!-- Sent from Reviewable.io -->

2022-10-01 19:17 UTC, BillAtBearGrove approved these changes
> Reviewed 2 of 6 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7)* status: all files reviewed, 18 unresolved discussions (waiting on @12tbuchman and @tracyofleming)



<!-- Sent from Reviewable.io -->

2022-10-02 19:44 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7)* status: all files reviewed, 18 unresolved discussions (waiting on @12tbuchman, @BillAtBearGrove, and @tracyofleming)

___
*[`-- commits` line 17 at r3](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFOjkY0gteA7TEtbXo):*
<details><summary><i>Previously, BillAtBearGrove (Bill Smith) wrote…</i></summary><blockquote>

This would be a good discussion - I would always recommend performing a commit at the end of a session. I wouldn't think these commits have to stand on their own at all. It's good practice to have backup in case your computer dies or you want to go back to an interim step if things go off the rails. I consider this one of the primary advantages of branching, so details aren't clouding the main branch. Is it OK to keep doing this and just merge back into the main when it's a "Stand-alone" and vetted change?
</blockquote></details>

you can definitely commit every day and i agree thats good practice. then before merging back to PR it is good practice to combine the commits into one or a few clean commits that can stand on their own - or in some situations where there is a large change it makes sense to split into smaller commits that dont necessarily stand on their own but each make a part of the overall change and then these can be merged back in with whats called a "merge commit". however in either case the commit history should be "cleaned up" before merging.


<!-- Sent from Reviewable.io -->

2022-10-02 19:52 UTC, 12tbuchman requested changes
> *[Reviewable](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7)* status: all files reviewed, 17 unresolved discussions (waiting on @12tbuchman, @BillAtBearGrove, and @tracyofleming)

___
*[`README.md` line 4 at r2](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFN_LHB0q4D88WX_zn:-NDPDolK8zI1P-AKV9Ls:br8g43f) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/9260141654a76cd0e12257c7eee6764dc1dd2645/README.md#L4)):*
<details><summary><i>Previously, BillAtBearGrove (Bill Smith) wrote…</i></summary><blockquote>

Meh - I'm not married to it if you have a good reason to drop it. My company always kept important steps recorded in a file that is not dependent on specific software (even GitHub) to be able to have an overview of changes.
</blockquote></details>

its not necessarily "bad" to have it if its properly maintained but if we look forward we hope to have many more developers working on this project who dont necessarily share the same principles of updating the changelog. so we should decide if we want to require this or not. if we dont require it then we should get rid of it to avoid putting out a deprecated changelog which can be confusing. if we want to require it thats fine, but i dont really see the point personally.
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 157 at r5](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFPFUQ0uuaaqsgjekG:-NDPE_ws2UZXQ4RFJn2E:b-l7nc14) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/c016c34cf2cbc4fdc05c8107b5413a2a1f22d98c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L157)):*
<details><summary><i>Previously, BillAtBearGrove (Bill Smith) wrote…</i></summary><blockquote>

Sure. it's good to delete if never used again, and OK to stay if we think they might be useful.
</blockquote></details>

do you think they will be useful? if so im fine keeping it
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 45 at r7](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFQozMBCM8Exgkdt3P:-NDPER1Y0Q4y7dF4bb0X:b-gdzc23) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/42aff1b7b66ea5898e9789abb6a819f8a632f04c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L45)):*
<details><summary><i>Previously, BillAtBearGrove (Bill Smith) wrote…</i></summary><blockquote>

LoL - Short answer - yes it is there "on purpose" But that's a bigger discussion I'd like to have b/c it's an artifact of the 1st few versions of code.
If it is removed, then filtering and rate limit calibrations will need to be changed.
It slows the code down by 50 ms which is intended to help it run a little more consistent for things like signal processing, noise and rate limiters. I think the normal execute time for the code is around 3ms and but varies quite a lot. Increasing the overall time means the impact in % is smaller - plus has added bonus of giving the Arduino a processing rest.

I've been meaning to get rid of that delay and setup protothreads w/ like 10ms, 100ms and 1s timers. Then split the code out to things that need to run fast and things that can run slow. Haven't had the time/guts yet, Not to mention I'm still learning how to implement this in Arduino. 
</blockquote></details>

i wasnt referring to the line `delay(50)`, i was referring to the line `o` below it
___
*[`ARISE_WildThing_MEGA/createJoystickTables.ino` line 54 at r5](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFQRC99A_HfeWP-_5x:-NDPFT9h5fhegq5B-3NL:b-7mhx9v) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/c016c34cf2cbc4fdc05c8107b5413a2a1f22d98c/ARISE_WildThing_MEGA/createJoystickTables.ino#L54)):*
<details><summary><i>Previously, BillAtBearGrove (Bill Smith) wrote…</i></summary><blockquote>

Or line up commas ;)
</blockquote></details>

no im not referring to within the braces, the line below has extra whitespace


<!-- Sent from Reviewable.io -->

2022-10-03 01:04 UTC, BillAtBearGrove approved these changes
> *[Reviewable](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7)* status: all files reviewed, 17 unresolved discussions (waiting on @12tbuchman, @BillAtBearGrove, and @tracyofleming)

___
*[`-- commits` line 17 at r3](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFOjkY0gteA7TEtbXo):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

you can definitely commit every day and i agree thats good practice. then before merging back to PR it is good practice to combine the commits into one or a few clean commits that can stand on their own - or in some situations where there is a large change it makes sense to split into smaller commits that dont necessarily stand on their own but each make a part of the overall change and then these can be merged back in with whats called a "merge commit". however in either case the commit history should be "cleaned up" before merging.
</blockquote></details>

Wait - are we talking about the same thing here? It's an option to squash all the commits as one when branch is merged. I'd prefer to do that.  Is that what you mean?
___
*[`-- commits` line 33 at r7](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFQvDKC1yfzFqalTyY):*
<details><summary><i>Previously, BillAtBearGrove (Bill Smith) wrote…</i></summary><blockquote>

might have rushed the commit. The description can be updated if required.
</blockquote></details>

I checked the commit - looks right to me based on the calibrations changed. "Retuned to remove bump on turn, improving mix." I'll leave the commit description
___
*[`README.md` line 4 at r2](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFN_LHB0q4D88WX_zn:-NDQGVtqBhI2Ss6rCkDX:b-mcu0t4) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/9260141654a76cd0e12257c7eee6764dc1dd2645/README.md#L4)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

its not necessarily "bad" to have it if its properly maintained but if we look forward we hope to have many more developers working on this project who dont necessarily share the same principles of updating the changelog. so we should decide if we want to require this or not. if we dont require it then we should get rid of it to avoid putting out a deprecated changelog which can be confusing. if we want to require it thats fine, but i dont really see the point personally.
</blockquote></details>

I'd be interested to hear what Tracy & Connor think. They don't get into GitHub too often, especially Connor. If he wants to know the differences in software versions it would be useful to have a text log.
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 157 at r5](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFPFUQ0uuaaqsgjekG:-NDQEHrC3vX1mWEYmm3i:bgza17m) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/c016c34cf2cbc4fdc05c8107b5413a2a1f22d98c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L157)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

do you think they will be useful? if so im fine keeping it
</blockquote></details>

Not super important to me either way.
___
*[`ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino` line 45 at r7](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFQozMBCM8Exgkdt3P:-NDQCVKuDSoleoVhJALW:b-3d1o8k) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/42aff1b7b66ea5898e9789abb6a819f8a632f04c/ARISE_WildThing_MEGA/ARISE_WildThing_MEGA.ino#L45)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

i wasnt referring to the line `delay(50)`, i was referring to the line `o` below it
</blockquote></details>

Nope. "o" Not supposed to be there. Surprised that it compiles OK with a stray "o" hanging about.
Also then disregard my comments on protothreading. I actually thought it was the delay() at the end loop() anyway. (unless that's a topic/discussion you're interested in)


<!-- Sent from Reviewable.io -->

2022-10-03 21:39 UTC, BillAtBearGrove approved these changes
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 2 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7)* status: all files reviewed, 17 unresolved discussions (waiting on @12tbuchman and @tracyofleming)

___
*[`ARISE_WildThing_MEGA/createJoystickTables.ino` line 54 at r5](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-NDFQRC99A_HfeWP-_5x:-NDUmBy6EAerXCDsPlPJ:b2ni9bh) ([raw file](https://github.com/ariseadaptivedesign/wildthing-collaboration/blob/c016c34cf2cbc4fdc05c8107b5413a2a1f22d98c/ARISE_WildThing_MEGA/createJoystickTables.ino#L54)):*
<details><summary><i>Previously, 12tbuchman (Tyler Buchman) wrote…</i></summary><blockquote>

no im not referring to within the braces, the line below has extra whitespace
</blockquote></details>

ok.


<!-- Sent from Reviewable.io -->

2022-12-09 21:25 UTC, 12tbuchman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> as discussed we are approving this PR and will follow regular PR practices moving forward

> *[Reviewable](https://reviewable.io/reviews/ariseadaptivedesign/wildthing-collaboration/7#-:-NIskvSZ8oTzYRY3-vKg:buvwkxn)* status: 5 of 9 files reviewed, 17 unresolved discussions (waiting on @BillAtBearGrove and @tracyofleming)



<!-- Sent from Reviewable.io -->

2022-12-09 21:25 UTC, merged